### ISSUE TITLE
hide previous button

### ISSUE THREAD

**Issue by wmehanna** [joeskeen/ng-enjoyhint#1]
i would like to have a way to hide the previous button when arrived to a particular step

**Comment by joeskeen** [comment]
I like that idea - shouldn't be too hard to implement. I have a couple bug fixes to make today, I'll see if I can add that too. Thanks for the suggestion @wmehanna!

**Comment by joeskeen** [comment]
I've implemented that here: https://github.com/joeskeen/ng-enjoyhint/commit/8a84934b4e18eafb78779d8598f461ab1bddaee0#diff-88a04c0085eff32dd3ac736b28a82b1c4e87bcefc06e21ce3399c8caa3f1fce3R92
I'm going to do a little more testing before I push out a release.

**Comment by joeskeen** [comment]
@wmehanna sorry for the delay, I've just pushed out a release.
